sudo: required
services:
  - docker

before_install:
  - docker build -t dockersamvi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dockersamvi/react-test npm test -- -- coverage

after_success:
  - docker build -t dockersamvi/multi-client ./client
  - docker build -t dockersamvi/multi-nginx ./nginx
  - docker build -t dockersamvi/multi-server ./server
  - docker build -t dockersamvi/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push stephengrider/multi-client
  - docker push stephengrider/multi-nginx
  - docker push stephengrider/multi-server
  - docker push stephengrider/multi-worker


